Security_site/security_site/security_site/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import *
from shifts.views import *
from salary.views import*
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homepage, name='home'),
    path('login/',login, name='login'),
    path('logout/',logout, name='logout'),
    path('profile/',profile_view,name='profile'),
    path('add_user/',add_user, name='add_user') ,
    path('add_shifts/',addShift.as_view(),name='add_shifts'),
    path('shifts/',ShiftsListView.as_view(),name='shifts'),
    path('shift/<int:pk>',ShiftDetalView.as_view(),name='shift'),
    path('shifts_for/',count_shist,name='shifts_for'),
    path('salarys/',salarys,name='salarys'),
    path('salary/<int:pk>',SalaryDetalView.as_view(),name='salary'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Security_site/security_site/salary/models.py
from django.db import models

# Create your models here.

Security_site/security_site/shifts/models.py
from django.db import models
from datetime import datetime
from django.core.exceptions import ValidationError
from django.forms.fields import DateField
from django.db.models.functions import TruncDate
from accounts.models import Employee
# Create your models here.

class TimeOfShift(models.Model):
    name = models.CharField(max_length=50,null=True)
    time = models.TimeField(validators=[ValidationError],null=True)
    price = models.IntegerField(null=True)

    def __str__(self) :
        return self.name


class Shift(models.Model):
    name = models.ForeignKey(Employee,on_delete=models.CASCADE,null=True)
    data_time = models.DateField(null=True)
    time_of_shift = models.ForeignKey(TimeOfShift,on_delete=models.CASCADE, null=True)

    def __str__(self) :
        return f'{self.name.first_name} {self.name.last_name}'

Security_site/security_site/salary/views.py
from django.shortcuts import render
from shifts.models import *
from django.contrib.auth.models import User
from accounts.models import Employee
from django.views.generic import  FormView, UpdateView, DeleteView, ListView ,DetailView
# Create your views here.

def salarys(request):
    employees = Employee.objects.all().order_by('shift')
    context = {
        'employees': employees,
    }
    return render(request, 'salary/salarys.html', context)


class SalaryDetalView(DetailView):
    template_name = 'salary/salary.html'
    model = Employee
    context_object_name = 'salary'

Security_site/security_site/templates/salary/salary.html
{% extends 'base.html' %}

{% block title %} | Salary {% endblock %}

{% block content %}

<ul class="card-header bg-dark" style="height: 100vh;">
    <br>
    <img src="{{salary.photo.url}}" height="250" width="200" />
    <p><h1 class="text-white"><u class="text-warning">Fullname:</u> {{ salary.first_name }} {{ salary.last_name }}</h1></p>
    <p><h2 class="text-white"><u class="text-warning">Email:</u> {{ salary.email }}</h2></p>
    <p><h2 class="text-white"><u class="text-warning">Phonenumber:</u> {{ salary.phone_number }}</h2></p>
</ul>

{% endblock content %}

Security_site/security_site/templates/salary/salarys.html
{% extends 'base.html' %}

{% block title %} | Salarys {% endblock %}

{% block content %}
<section class="bg-dark py-5" >
    <ul>
        {% for employee in employees %}
            <a href="{%url 'salary' employee.id%}" class="link-warning"><h2 class="text-warning ">{{ employee.first_name }} {{ employee.last_name }}:</h2></a>
            {% for shift in employee.shift_set.all %}
                <h4 class="text-white">{{ shift.time_of_shift }}, {{ shift.data_time }} - {{ shift.time_of_shift.price }}₪</h4>
            {% endfor %}
        {% endfor %}
    </ul> 
</section>

{% endblock content %}